// This file is autogenerated by the hrpc compiler
/* eslint-disable camelcase */
/* eslint-disable space-before-function-paren */

const { c, RPC, RPCStream, RPCRequestStream } = require('hrpc/runtime')
const { getEncoding } = require('./messages.js')

const methods = new Map([
  ['@bareclaw/chat', 0],
  [0, '@bareclaw/chat'],
  ['@bareclaw/session-create', 1],
  [1, '@bareclaw/session-create'],
  ['@bareclaw/session-list', 2],
  [2, '@bareclaw/session-list'],
  ['@bareclaw/session-export', 3],
  [3, '@bareclaw/session-export'],
  ['@bareclaw/session-import', 4],
  [4, '@bareclaw/session-import'],
  ['@bareclaw/state-export', 5],
  [5, '@bareclaw/state-export'],
  ['@bareclaw/state-import', 6],
  [6, '@bareclaw/state-import'],
  ['@bareclaw/tool-register', 7],
  [7, '@bareclaw/tool-register'],
  ['@bareclaw/tool-exec', 8],
  [8, '@bareclaw/tool-exec'],
  ['@bareclaw/state-changed', 9],
  [9, '@bareclaw/state-changed']
])

class HRPC {
  constructor(stream) {
    this._stream = stream
    this._handlers = []
    this._requestEncodings = new Map([
      ['@bareclaw/chat', getEncoding('@bareclaw/chat-request')],
      ['@bareclaw/session-create', getEncoding('@bareclaw/session-scope')],
      ['@bareclaw/session-list', getEncoding('@bareclaw/empty')],
      ['@bareclaw/session-export', getEncoding('@bareclaw/session-key')],
      ['@bareclaw/session-import', getEncoding('@bareclaw/session-blob')],
      ['@bareclaw/state-export', getEncoding('@bareclaw/empty')],
      ['@bareclaw/state-import', getEncoding('@bareclaw/state-blob')],
      ['@bareclaw/tool-register', getEncoding('@bareclaw/tool-def')],
      ['@bareclaw/tool-exec', getEncoding('@bareclaw/tool-call')],
      ['@bareclaw/state-changed', getEncoding('@bareclaw/state-chunk')]
    ])
    this._responseEncodings = new Map([
      ['@bareclaw/chat', getEncoding('@bareclaw/chat-chunk')],
      ['@bareclaw/session-create', getEncoding('@bareclaw/session-key')],
      ['@bareclaw/session-list', getEncoding('@bareclaw/session-list')],
      ['@bareclaw/session-export', getEncoding('@bareclaw/session-blob')],
      ['@bareclaw/session-import', getEncoding('@bareclaw/empty')],
      ['@bareclaw/state-export', getEncoding('@bareclaw/state-blob')],
      ['@bareclaw/state-import', getEncoding('@bareclaw/empty')],
      ['@bareclaw/tool-register', getEncoding('@bareclaw/empty')],
      ['@bareclaw/tool-exec', getEncoding('@bareclaw/tool-result')]
    ])
    this._rpc = new RPC(stream, async (req) => {
      const command = methods.get(req.command)
      const responseEncoding = this._responseEncodings.get(command)
      const requestEncoding = this._requestEncodings.get(command)
      if (this._requestIsSend(command)) {
        const request = req.data && req.data.byteLength > 0 ? c.decode(requestEncoding, req.data) : null
        await this._handlers[command](request)
        return
      }
      if (!this._requestIsStream(command) && !this._responseIsStream(command)) {
        const request = req.data && req.data.byteLength > 0 ? c.decode(requestEncoding, req.data) : null
        const response = await this._handlers[command](request)
        req.reply(c.encode(responseEncoding, response))
      }
      if (!this._requestIsStream(command) && this._responseIsStream(command)) {
        const request = req.data && req.data.byteLength > 0 ? c.decode(requestEncoding, req.data) : null
        const responseStream = new RPCStream(
          null,
          null,
          req.createResponseStream(),
          responseEncoding
        )
        responseStream.data = request
        await this._handlers[command](responseStream)
      }
      if (this._requestIsStream(command) && !this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding
        )
        const response = await this._handlers[command](requestStream)
        req.reply(c.encode(responseEncoding, response))
      }
      if (this._requestIsStream(command) && this._responseIsStream(command)) {
        const requestStream = new RPCRequestStream(
          req,
          responseEncoding,
          req.createRequestStream(),
          requestEncoding,
          req.createResponseStream(),
          responseEncoding
        )
        await this._handlers[command](requestStream)
      }
    })
  }

  async _call(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    const request = this._rpc.request(methods.get(name))
    const encoded = c.encode(requestEncoding, args)
    request.send(encoded)
    return c.decode(responseEncoding, await request.reply())
  }

  _callSync(name, args) {
    const requestEncoding = this._requestEncodings.get(name)
    const responseEncoding = this._responseEncodings.get(name)
    if (this._requestIsSend(name)) {
      const encoded = c.encode(requestEncoding, args)
      const request = this._rpc.event(methods.get(name))
      request.send(encoded)
    }

    const request = this._rpc.request(methods.get(name))

    if (!this._requestIsStream(name) && this._responseIsStream(name)) {
      const encoded = c.encode(requestEncoding, args)
      request.send(encoded)
      return new RPCStream(request.createResponseStream(), responseEncoding)
    }
    if (this._requestIsStream(name) && !this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        null,
        null,
        request.createRequestStream(),
        requestEncoding
      )
    }
    if (this._requestIsStream(name) && this._responseIsStream(name)) {
      return new RPCRequestStream(
        request,
        responseEncoding,
        request.createResponseStream(),
        responseEncoding,
        request.createRequestStream(),
        requestEncoding
      )
    }
  }

  chat(args) {
    return this._callSync('@bareclaw/chat', args)
  }

  async sessionCreate(args) {
    return this._call('@bareclaw/session-create', args)
  }

  async sessionList(args) {
    return this._call('@bareclaw/session-list', args)
  }

  async sessionExport(args) {
    return this._call('@bareclaw/session-export', args)
  }

  async sessionImport(args) {
    return this._call('@bareclaw/session-import', args)
  }

  async stateExport(args) {
    return this._call('@bareclaw/state-export', args)
  }

  async stateImport(args) {
    return this._call('@bareclaw/state-import', args)
  }

  async toolRegister(args) {
    return this._call('@bareclaw/tool-register', args)
  }

  async toolExec(args) {
    return this._call('@bareclaw/tool-exec', args)
  }

  stateChanged(args) {
    return this._callSync('@bareclaw/state-changed', args)
  }

  onChat(responseFn) {
    this._handlers['@bareclaw/chat'] = responseFn
  }

  onSessionCreate(responseFn) {
    this._handlers['@bareclaw/session-create'] = responseFn
  }

  onSessionList(responseFn) {
    this._handlers['@bareclaw/session-list'] = responseFn
  }

  onSessionExport(responseFn) {
    this._handlers['@bareclaw/session-export'] = responseFn
  }

  onSessionImport(responseFn) {
    this._handlers['@bareclaw/session-import'] = responseFn
  }

  onStateExport(responseFn) {
    this._handlers['@bareclaw/state-export'] = responseFn
  }

  onStateImport(responseFn) {
    this._handlers['@bareclaw/state-import'] = responseFn
  }

  onToolRegister(responseFn) {
    this._handlers['@bareclaw/tool-register'] = responseFn
  }

  onToolExec(responseFn) {
    this._handlers['@bareclaw/tool-exec'] = responseFn
  }

  onStateChanged(responseFn) {
    this._handlers['@bareclaw/state-changed'] = responseFn
  }

  _requestIsStream(command) {
    return [
    ].includes(command)
  }

  _responseIsStream(command) {
    return [
      '@bareclaw/chat'
    ].includes(command)
  }

  // prettier-ignore-start
  _requestIsSend(command) {
    return [
      // prettier-ignore
      '@bareclaw/state-changed'
    ].includes(command)
  }
}

module.exports = HRPC
