// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */
/* eslint-disable space-before-function-paren */

const { c } = require('hyperschema/runtime')

const VERSION = 1

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @bareclaw/empty
const encoding0 = {
  preencode(state, m) {

  },
  encode(state, m) {

  },
  decode(state) {
    return {
    }
  }
}

// @bareclaw/chat-request
const encoding1 = {
  preencode(state, m) {
    c.string.preencode(state, m.sessionId)
    c.string.preencode(state, m.message)
    state.end++ // max flag is 1 so always one byte

    if (m.model) c.string.preencode(state, m.model)
  },
  encode(state, m) {
    const flags = m.model ? 1 : 0

    c.string.encode(state, m.sessionId)
    c.string.encode(state, m.message)
    c.uint.encode(state, flags)

    if (m.model) c.string.encode(state, m.model)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      sessionId: r0,
      message: r1,
      model: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

const encoding2_enum = {
  content: 'content',
  thinking: 'thinking',
  done: 'done',
  error: 'error'
}

// @bareclaw/chunk-type enum
const encoding2 = {
  preencode (state, m) {
    state.end++ // max enum is 4 so always one byte
  },
  encode (state, m) {
    switch (m) {
      case 'content':
        c.uint.encode(state, 1)
        break
      case 'thinking':
        c.uint.encode(state, 2)
        break
      case 'done':
        c.uint.encode(state, 3)
        break
      case 'error':
        c.uint.encode(state, 4)
        break
      default:
        throw new Error('Unknown enum')
    }
  },
  decode (state) {
    switch (c.uint.decode(state)) {
      case 1:
        return 'content'
      case 2:
        return 'thinking'
      case 3:
        return 'done'
      case 4:
        return 'error'
      default: return null
    }
  }
}

// @bareclaw/chat-chunk
const encoding3 = {
  preencode(state, m) {
    encoding2.preencode(state, m.type)
    state.end++ // max flag is 1 so always one byte

    if (m.content) c.string.preencode(state, m.content)
  },
  encode(state, m) {
    const flags = m.content ? 1 : 0

    encoding2.encode(state, m.type)
    c.uint.encode(state, flags)

    if (m.content) c.string.encode(state, m.content)
  },
  decode(state) {
    const r0 = encoding2.decode(state)
    const flags = c.uint.decode(state)

    return {
      type: r0,
      content: (flags & 1) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bareclaw/session-scope
const encoding4 = {
  preencode(state, m) {
    state.end++ // max flag is 8 so always one byte

    if (m.agentId) c.string.preencode(state, m.agentId)
    if (m.channel) c.string.preencode(state, m.channel)
    if (m.account) c.string.preencode(state, m.account)
    if (m.peer) c.string.preencode(state, m.peer)
  },
  encode(state, m) {
    const flags = (m.agentId ? 1 : 0) | (m.channel ? 2 : 0) | (m.account ? 4 : 0) | (m.peer ? 8 : 0)

    c.uint.encode(state, flags)

    if (m.agentId) c.string.encode(state, m.agentId)
    if (m.channel) c.string.encode(state, m.channel)
    if (m.account) c.string.encode(state, m.account)
    if (m.peer) c.string.encode(state, m.peer)
  },
  decode(state) {
    const flags = c.uint.decode(state)

    return {
      agentId: (flags & 1) !== 0 ? c.string.decode(state) : null,
      channel: (flags & 2) !== 0 ? c.string.decode(state) : null,
      account: (flags & 4) !== 0 ? c.string.decode(state) : null,
      peer: (flags & 8) !== 0 ? c.string.decode(state) : null
    }
  }
}

// @bareclaw/session-key
const encoding5 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
  },
  decode(state) {
    const r0 = c.string.decode(state)

    return {
      key: r0
    }
  }
}

// @bareclaw/session-list.keys
const encoding6_0 = c.array(c.string)

// @bareclaw/session-list
const encoding6 = {
  preencode(state, m) {
    encoding6_0.preencode(state, m.keys)
  },
  encode(state, m) {
    encoding6_0.encode(state, m.keys)
  },
  decode(state) {
    const r0 = encoding6_0.decode(state)

    return {
      keys: r0
    }
  }
}

// @bareclaw/session-blob
const encoding7 = {
  preencode(state, m) {
    c.string.preencode(state, m.key)
    c.buffer.preencode(state, m.data)
  },
  encode(state, m) {
    c.string.encode(state, m.key)
    c.buffer.encode(state, m.data)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.buffer.decode(state)

    return {
      key: r0,
      data: r1
    }
  }
}

// @bareclaw/state-blob.sessions
const encoding8_0 = c.array(c.frame(encoding7))

// @bareclaw/state-blob
const encoding8 = {
  preencode(state, m) {
    encoding8_0.preencode(state, m.sessions)
  },
  encode(state, m) {
    encoding8_0.encode(state, m.sessions)
  },
  decode(state) {
    const r0 = encoding8_0.decode(state)

    return {
      sessions: r0
    }
  }
}

// @bareclaw/tool-def
const encoding9 = {
  preencode(state, m) {
    c.string.preencode(state, m.name)
    c.string.preencode(state, m.description)
    state.end++ // max flag is 1 so always one byte

    if (m.inputSchema) c.buffer.preencode(state, m.inputSchema)
  },
  encode(state, m) {
    const flags = m.inputSchema ? 1 : 0

    c.string.encode(state, m.name)
    c.string.encode(state, m.description)
    c.uint.encode(state, flags)

    if (m.inputSchema) c.buffer.encode(state, m.inputSchema)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      name: r0,
      description: r1,
      inputSchema: (flags & 1) !== 0 ? c.buffer.decode(state) : null
    }
  }
}

// @bareclaw/tool-call
const encoding10 = {
  preencode(state, m) {
    c.string.preencode(state, m.callId)
    c.string.preencode(state, m.name)
    c.buffer.preencode(state, m.input)
  },
  encode(state, m) {
    c.string.encode(state, m.callId)
    c.string.encode(state, m.name)
    c.buffer.encode(state, m.input)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.buffer.decode(state)

    return {
      callId: r0,
      name: r1,
      input: r2
    }
  }
}

// @bareclaw/tool-result
const encoding11 = {
  preencode(state, m) {
    c.string.preencode(state, m.callId)
    state.end++ // max flag is 2 so always one byte

    if (m.output) c.buffer.preencode(state, m.output)
    if (m.errMsg) c.string.preencode(state, m.errMsg)
  },
  encode(state, m) {
    const flags = (m.output ? 1 : 0) | (m.errMsg ? 2 : 0)

    c.string.encode(state, m.callId)
    c.uint.encode(state, flags)

    if (m.output) c.buffer.encode(state, m.output)
    if (m.errMsg) c.string.encode(state, m.errMsg)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      callId: r0,
      output: (flags & 1) !== 0 ? c.buffer.decode(state) : null,
      errMsg: (flags & 2) !== 0 ? c.string.decode(state) : null
    }
  }
}

const encoding12_enum = {
  history: 'history',
  summary: 'summary'
}

// @bareclaw/state-field enum
const encoding12 = {
  preencode (state, m) {
    state.end++ // max enum is 2 so always one byte
  },
  encode (state, m) {
    switch (m) {
      case 'history':
        c.uint.encode(state, 1)
        break
      case 'summary':
        c.uint.encode(state, 2)
        break
      default:
        throw new Error('Unknown enum')
    }
  },
  decode (state) {
    switch (c.uint.decode(state)) {
      case 1:
        return 'history'
      case 2:
        return 'summary'
      default: return null
    }
  }
}

// @bareclaw/state-chunk
const encoding13 = {
  preencode(state, m) {
    c.string.preencode(state, m.sessionKey)
    encoding12.preencode(state, m.field)
    c.buffer.preencode(state, m.data)
  },
  encode(state, m) {
    c.string.encode(state, m.sessionKey)
    encoding12.encode(state, m.field)
    c.buffer.encode(state, m.data)
  },
  decode(state) {
    const r0 = c.string.decode(state)
    const r1 = encoding12.decode(state)
    const r2 = c.buffer.decode(state)

    return {
      sessionKey: r0,
      field: r1,
      data: r2
    }
  }
}

function setVersion(v) {
  version = v
}

function encode(name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode(name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum(name) {
  switch (name) {
    case '@bareclaw/chunk-type':
      return encoding2_enum
    case '@bareclaw/state-field':
      return encoding12_enum
    default:
      throw new Error('Enum not found ' + name)
  }
}

function getEncoding(name) {
  switch (name) {
    case '@bareclaw/empty':
      return encoding0
    case '@bareclaw/chat-request':
      return encoding1
    case '@bareclaw/chunk-type':
      return encoding2
    case '@bareclaw/chat-chunk':
      return encoding3
    case '@bareclaw/session-scope':
      return encoding4
    case '@bareclaw/session-key':
      return encoding5
    case '@bareclaw/session-list':
      return encoding6
    case '@bareclaw/session-blob':
      return encoding7
    case '@bareclaw/state-blob':
      return encoding8
    case '@bareclaw/tool-def':
      return encoding9
    case '@bareclaw/tool-call':
      return encoding10
    case '@bareclaw/tool-result':
      return encoding11
    case '@bareclaw/state-field':
      return encoding12
    case '@bareclaw/state-chunk':
      return encoding13
    default:
      throw new Error('Encoder not found ' + name)
  }
}

function getStruct(name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode(state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode(state, m) {
      version = v
      enc.encode(state, m)
    },
    decode(state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = {
  resolveStruct,
  getStruct,
  getEnum,
  getEncoding,
  encode,
  decode,
  setVersion,
  version
}
