// This file is autogenerated by the hyperschema-golang compiler
package schema

import (
	"errors"

	cenc "github.com/holepunchto/compact-encoding-golang"
)

// Version is the schema version this package was generated from.
const Version = 1

var errUnknownEnum = errors.New("hyperschema: unknown enum value")

// BareclawEmpty is @bareclaw/empty.
type BareclawEmpty struct {
}

func (m *BareclawEmpty) Preencode(state *cenc.State) {
}

func (m *BareclawEmpty) Encode(state *cenc.State) error {
	return nil
}

func (m *BareclawEmpty) Decode(state *cenc.State) error {
	var err error
	return err
}

// BareclawChatRequest is @bareclaw/chat-request.
type BareclawChatRequest struct {
	SessionId string `json:"sessionId"`
	Message   string `json:"message"`
	Model     string `json:"model"`
}

func (m *BareclawChatRequest) Preencode(state *cenc.State) {
	var flags uint
	if m.Model != "" {
		flags |= 1
	}
	cenc.NewString().Preencode(state, m.SessionId)
	cenc.NewString().Preencode(state, m.Message)
	cenc.NewUint().Preencode(state, flags)
	if m.Model != "" {
		cenc.NewString().Preencode(state, m.Model)
	}
}

func (m *BareclawChatRequest) Encode(state *cenc.State) error {
	var flags uint
	if m.Model != "" {
		flags |= 1
	}
	if err := cenc.NewString().Encode(state, m.SessionId); err != nil {
		return err
	}
	if err := cenc.NewString().Encode(state, m.Message); err != nil {
		return err
	}
	if err := cenc.NewUint().Encode(state, flags); err != nil {
		return err
	}
	if m.Model != "" {
		if err := cenc.NewString().Encode(state, m.Model); err != nil {
			return err
		}
	}
	return nil
}

func (m *BareclawChatRequest) Decode(state *cenc.State) error {
	var err error
	if m.SessionId, err = cenc.NewString().Decode(state); err != nil {
		return err
	}
	if m.Message, err = cenc.NewString().Decode(state); err != nil {
		return err
	}
	var flags uint
	if flags, err = cenc.NewUint().Decode(state); err != nil {
		return err
	}
	if flags&1 != 0 {
		if m.Model, err = cenc.NewString().Decode(state); err != nil {
			return err
		}
	}
	return err
}

// BareclawChunkType is @bareclaw/chunk-type.
type BareclawChunkType string

const BareclawChunkTypeContent BareclawChunkType = "content"
const BareclawChunkTypeThinking BareclawChunkType = "thinking"
const BareclawChunkTypeDone BareclawChunkType = "done"
const BareclawChunkTypeError BareclawChunkType = "error"

func (m *BareclawChunkType) index() (uint, bool) {
	switch *m {
	case BareclawChunkTypeContent:
		return 1, true
	case BareclawChunkTypeThinking:
		return 2, true
	case BareclawChunkTypeDone:
		return 3, true
	case BareclawChunkTypeError:
		return 4, true
	}
	return 0, false
}

func (m *BareclawChunkType) Preencode(state *cenc.State) {
	n, _ := m.index()
	cenc.NewUint().Preencode(state, n)
}

func (m *BareclawChunkType) Encode(state *cenc.State) error {
	n, ok := m.index()
	if !ok {
		return errUnknownEnum
	}
	return cenc.NewUint().Encode(state, n)
}

func (m *BareclawChunkType) Decode(state *cenc.State) error {
	n, err := cenc.NewUint().Decode(state)
	if err != nil {
		return err
	}
	switch n {
	case 1:
		*m = BareclawChunkTypeContent
	case 2:
		*m = BareclawChunkTypeThinking
	case 3:
		*m = BareclawChunkTypeDone
	case 4:
		*m = BareclawChunkTypeError
	default:
		*m = ""
	}
	return nil
}

// BareclawChatChunk is @bareclaw/chat-chunk.
type BareclawChatChunk struct {
	Type    BareclawChunkType `json:"type"`
	Content string            `json:"content"`
}

func (m *BareclawChatChunk) Preencode(state *cenc.State) {
	var flags uint
	if m.Content != "" {
		flags |= 1
	}
	m.Type.Preencode(state)
	cenc.NewUint().Preencode(state, flags)
	if m.Content != "" {
		cenc.NewString().Preencode(state, m.Content)
	}
}

func (m *BareclawChatChunk) Encode(state *cenc.State) error {
	var flags uint
	if m.Content != "" {
		flags |= 1
	}
	if err := m.Type.Encode(state); err != nil {
		return err
	}
	if err := cenc.NewUint().Encode(state, flags); err != nil {
		return err
	}
	if m.Content != "" {
		if err := cenc.NewString().Encode(state, m.Content); err != nil {
			return err
		}
	}
	return nil
}

func (m *BareclawChatChunk) Decode(state *cenc.State) error {
	var err error
	if err := m.Type.Decode(state); err != nil {
		return err
	}
	var flags uint
	if flags, err = cenc.NewUint().Decode(state); err != nil {
		return err
	}
	if flags&1 != 0 {
		if m.Content, err = cenc.NewString().Decode(state); err != nil {
			return err
		}
	}
	return err
}

// BareclawSessionScope is @bareclaw/session-scope.
type BareclawSessionScope struct {
	AgentId string `json:"agentId"`
	Channel string `json:"channel"`
	Account string `json:"account"`
	Peer    string `json:"peer"`
}

func (m *BareclawSessionScope) Preencode(state *cenc.State) {
	var flags uint
	if m.AgentId != "" {
		flags |= 1
	}
	if m.Channel != "" {
		flags |= 2
	}
	if m.Account != "" {
		flags |= 4
	}
	if m.Peer != "" {
		flags |= 8
	}
	cenc.NewUint().Preencode(state, flags)
	if m.AgentId != "" {
		cenc.NewString().Preencode(state, m.AgentId)
	}
	if m.Channel != "" {
		cenc.NewString().Preencode(state, m.Channel)
	}
	if m.Account != "" {
		cenc.NewString().Preencode(state, m.Account)
	}
	if m.Peer != "" {
		cenc.NewString().Preencode(state, m.Peer)
	}
}

func (m *BareclawSessionScope) Encode(state *cenc.State) error {
	var flags uint
	if m.AgentId != "" {
		flags |= 1
	}
	if m.Channel != "" {
		flags |= 2
	}
	if m.Account != "" {
		flags |= 4
	}
	if m.Peer != "" {
		flags |= 8
	}
	if err := cenc.NewUint().Encode(state, flags); err != nil {
		return err
	}
	if m.AgentId != "" {
		if err := cenc.NewString().Encode(state, m.AgentId); err != nil {
			return err
		}
	}
	if m.Channel != "" {
		if err := cenc.NewString().Encode(state, m.Channel); err != nil {
			return err
		}
	}
	if m.Account != "" {
		if err := cenc.NewString().Encode(state, m.Account); err != nil {
			return err
		}
	}
	if m.Peer != "" {
		if err := cenc.NewString().Encode(state, m.Peer); err != nil {
			return err
		}
	}
	return nil
}

func (m *BareclawSessionScope) Decode(state *cenc.State) error {
	var err error
	var flags uint
	if flags, err = cenc.NewUint().Decode(state); err != nil {
		return err
	}
	if flags&1 != 0 {
		if m.AgentId, err = cenc.NewString().Decode(state); err != nil {
			return err
		}
	}
	if flags&2 != 0 {
		if m.Channel, err = cenc.NewString().Decode(state); err != nil {
			return err
		}
	}
	if flags&4 != 0 {
		if m.Account, err = cenc.NewString().Decode(state); err != nil {
			return err
		}
	}
	if flags&8 != 0 {
		if m.Peer, err = cenc.NewString().Decode(state); err != nil {
			return err
		}
	}
	return err
}

// BareclawSessionKey is @bareclaw/session-key.
type BareclawSessionKey struct {
	Key string `json:"key"`
}

func (m *BareclawSessionKey) Preencode(state *cenc.State) {
	cenc.NewString().Preencode(state, m.Key)
}

func (m *BareclawSessionKey) Encode(state *cenc.State) error {
	if err := cenc.NewString().Encode(state, m.Key); err != nil {
		return err
	}
	return nil
}

func (m *BareclawSessionKey) Decode(state *cenc.State) error {
	var err error
	if m.Key, err = cenc.NewString().Decode(state); err != nil {
		return err
	}
	return err
}

// BareclawSessionList is @bareclaw/session-list.
type BareclawSessionList struct {
	Keys []string `json:"keys"`
}

func (m *BareclawSessionList) Preencode(state *cenc.State) {
	cenc.NewUint().Preencode(state, uint(len(m.Keys)))
	for i := range m.Keys {
		cenc.NewString().Preencode(state, m.Keys[i])
	}
}

func (m *BareclawSessionList) Encode(state *cenc.State) error {
	if err := cenc.NewUint().Encode(state, uint(len(m.Keys))); err != nil {
		return err
	}
	for i := range m.Keys {
		if err := cenc.NewString().Encode(state, m.Keys[i]); err != nil {
			return err
		}
	}
	return nil
}

func (m *BareclawSessionList) Decode(state *cenc.State) error {
	var err error
	if n, err := cenc.NewUint().Decode(state); err != nil {
		return err
	} else if n > cenc.MaxArrayLength {
		return cenc.NewEncodingErrorArrayTooBig()
	} else {
		m.Keys = make([]string, n)
	}
	for i := range m.Keys {
		if m.Keys[i], err = cenc.NewString().Decode(state); err != nil {
			return err
		}
	}
	return err
}

// BareclawSessionBlob is @bareclaw/session-blob.
type BareclawSessionBlob struct {
	Key  string `json:"key"`
	Data []byte `json:"data"`
}

func (m *BareclawSessionBlob) Preencode(state *cenc.State) {
	cenc.NewString().Preencode(state, m.Key)
	cenc.NewBuffer().Preencode(state, m.Data)
}

func (m *BareclawSessionBlob) Encode(state *cenc.State) error {
	if err := cenc.NewString().Encode(state, m.Key); err != nil {
		return err
	}
	if err := cenc.NewBuffer().Encode(state, m.Data); err != nil {
		return err
	}
	return nil
}

func (m *BareclawSessionBlob) Decode(state *cenc.State) error {
	var err error
	if m.Key, err = cenc.NewString().Decode(state); err != nil {
		return err
	}
	if m.Data, err = cenc.NewBuffer().Decode(state); err != nil {
		return err
	}
	return err
}

// BareclawStateBlob is @bareclaw/state-blob.
type BareclawStateBlob struct {
	Sessions []BareclawSessionBlob `json:"sessions"`
}

func (m *BareclawStateBlob) Preencode(state *cenc.State) {
	cenc.NewUint().Preencode(state, uint(len(m.Sessions)))
	for i := range m.Sessions {
		preencodeFrame(state, &m.Sessions[i])
	}
}

func (m *BareclawStateBlob) Encode(state *cenc.State) error {
	if err := cenc.NewUint().Encode(state, uint(len(m.Sessions))); err != nil {
		return err
	}
	for i := range m.Sessions {
		if err := encodeFrame(state, &m.Sessions[i]); err != nil {
			return err
		}
	}
	return nil
}

func (m *BareclawStateBlob) Decode(state *cenc.State) error {
	var err error
	if n, err := cenc.NewUint().Decode(state); err != nil {
		return err
	} else if n > cenc.MaxArrayLength {
		return cenc.NewEncodingErrorArrayTooBig()
	} else {
		m.Sessions = make([]BareclawSessionBlob, n)
	}
	for i := range m.Sessions {
		if err := decodeFrame(state, &m.Sessions[i]); err != nil {
			return err
		}
	}
	return err
}

// BareclawToolDef is @bareclaw/tool-def.
type BareclawToolDef struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	InputSchema []byte `json:"inputSchema"`
}

func (m *BareclawToolDef) Preencode(state *cenc.State) {
	var flags uint
	if m.InputSchema != nil {
		flags |= 1
	}
	cenc.NewString().Preencode(state, m.Name)
	cenc.NewString().Preencode(state, m.Description)
	cenc.NewUint().Preencode(state, flags)
	if m.InputSchema != nil {
		cenc.NewBuffer().Preencode(state, m.InputSchema)
	}
}

func (m *BareclawToolDef) Encode(state *cenc.State) error {
	var flags uint
	if m.InputSchema != nil {
		flags |= 1
	}
	if err := cenc.NewString().Encode(state, m.Name); err != nil {
		return err
	}
	if err := cenc.NewString().Encode(state, m.Description); err != nil {
		return err
	}
	if err := cenc.NewUint().Encode(state, flags); err != nil {
		return err
	}
	if m.InputSchema != nil {
		if err := cenc.NewBuffer().Encode(state, m.InputSchema); err != nil {
			return err
		}
	}
	return nil
}

func (m *BareclawToolDef) Decode(state *cenc.State) error {
	var err error
	if m.Name, err = cenc.NewString().Decode(state); err != nil {
		return err
	}
	if m.Description, err = cenc.NewString().Decode(state); err != nil {
		return err
	}
	var flags uint
	if flags, err = cenc.NewUint().Decode(state); err != nil {
		return err
	}
	if flags&1 != 0 {
		if m.InputSchema, err = cenc.NewBuffer().Decode(state); err != nil {
			return err
		}
	}
	return err
}

// BareclawToolCall is @bareclaw/tool-call.
type BareclawToolCall struct {
	CallId string `json:"callId"`
	Name   string `json:"name"`
	Input  []byte `json:"input"`
}

func (m *BareclawToolCall) Preencode(state *cenc.State) {
	cenc.NewString().Preencode(state, m.CallId)
	cenc.NewString().Preencode(state, m.Name)
	cenc.NewBuffer().Preencode(state, m.Input)
}

func (m *BareclawToolCall) Encode(state *cenc.State) error {
	if err := cenc.NewString().Encode(state, m.CallId); err != nil {
		return err
	}
	if err := cenc.NewString().Encode(state, m.Name); err != nil {
		return err
	}
	if err := cenc.NewBuffer().Encode(state, m.Input); err != nil {
		return err
	}
	return nil
}

func (m *BareclawToolCall) Decode(state *cenc.State) error {
	var err error
	if m.CallId, err = cenc.NewString().Decode(state); err != nil {
		return err
	}
	if m.Name, err = cenc.NewString().Decode(state); err != nil {
		return err
	}
	if m.Input, err = cenc.NewBuffer().Decode(state); err != nil {
		return err
	}
	return err
}

// BareclawToolResult is @bareclaw/tool-result.
type BareclawToolResult struct {
	CallId string `json:"callId"`
	Output []byte `json:"output"`
	ErrMsg string `json:"errMsg"`
}

func (m *BareclawToolResult) Preencode(state *cenc.State) {
	var flags uint
	if m.Output != nil {
		flags |= 1
	}
	if m.ErrMsg != "" {
		flags |= 2
	}
	cenc.NewString().Preencode(state, m.CallId)
	cenc.NewUint().Preencode(state, flags)
	if m.Output != nil {
		cenc.NewBuffer().Preencode(state, m.Output)
	}
	if m.ErrMsg != "" {
		cenc.NewString().Preencode(state, m.ErrMsg)
	}
}

func (m *BareclawToolResult) Encode(state *cenc.State) error {
	var flags uint
	if m.Output != nil {
		flags |= 1
	}
	if m.ErrMsg != "" {
		flags |= 2
	}
	if err := cenc.NewString().Encode(state, m.CallId); err != nil {
		return err
	}
	if err := cenc.NewUint().Encode(state, flags); err != nil {
		return err
	}
	if m.Output != nil {
		if err := cenc.NewBuffer().Encode(state, m.Output); err != nil {
			return err
		}
	}
	if m.ErrMsg != "" {
		if err := cenc.NewString().Encode(state, m.ErrMsg); err != nil {
			return err
		}
	}
	return nil
}

func (m *BareclawToolResult) Decode(state *cenc.State) error {
	var err error
	if m.CallId, err = cenc.NewString().Decode(state); err != nil {
		return err
	}
	var flags uint
	if flags, err = cenc.NewUint().Decode(state); err != nil {
		return err
	}
	if flags&1 != 0 {
		if m.Output, err = cenc.NewBuffer().Decode(state); err != nil {
			return err
		}
	}
	if flags&2 != 0 {
		if m.ErrMsg, err = cenc.NewString().Decode(state); err != nil {
			return err
		}
	}
	return err
}

// BareclawStateField is @bareclaw/state-field.
type BareclawStateField string

const BareclawStateFieldHistory BareclawStateField = "history"
const BareclawStateFieldSummary BareclawStateField = "summary"

func (m *BareclawStateField) index() (uint, bool) {
	switch *m {
	case BareclawStateFieldHistory:
		return 1, true
	case BareclawStateFieldSummary:
		return 2, true
	}
	return 0, false
}

func (m *BareclawStateField) Preencode(state *cenc.State) {
	n, _ := m.index()
	cenc.NewUint().Preencode(state, n)
}

func (m *BareclawStateField) Encode(state *cenc.State) error {
	n, ok := m.index()
	if !ok {
		return errUnknownEnum
	}
	return cenc.NewUint().Encode(state, n)
}

func (m *BareclawStateField) Decode(state *cenc.State) error {
	n, err := cenc.NewUint().Decode(state)
	if err != nil {
		return err
	}
	switch n {
	case 1:
		*m = BareclawStateFieldHistory
	case 2:
		*m = BareclawStateFieldSummary
	default:
		*m = ""
	}
	return nil
}

// BareclawStateChunk is @bareclaw/state-chunk.
type BareclawStateChunk struct {
	SessionKey string             `json:"sessionKey"`
	Field      BareclawStateField `json:"field"`
	Data       []byte             `json:"data"`
}

func (m *BareclawStateChunk) Preencode(state *cenc.State) {
	cenc.NewString().Preencode(state, m.SessionKey)
	m.Field.Preencode(state)
	cenc.NewBuffer().Preencode(state, m.Data)
}

func (m *BareclawStateChunk) Encode(state *cenc.State) error {
	if err := cenc.NewString().Encode(state, m.SessionKey); err != nil {
		return err
	}
	if err := m.Field.Encode(state); err != nil {
		return err
	}
	if err := cenc.NewBuffer().Encode(state, m.Data); err != nil {
		return err
	}
	return nil
}

func (m *BareclawStateChunk) Decode(state *cenc.State) error {
	var err error
	if m.SessionKey, err = cenc.NewString().Decode(state); err != nil {
		return err
	}
	if err := m.Field.Decode(state); err != nil {
		return err
	}
	if m.Data, err = cenc.NewBuffer().Decode(state); err != nil {
		return err
	}
	return err
}

// Non-compact structs are framed inside other values: a length prefix, then the struct.
func frameSize(m cenc.Marshaler) uint {
	s := cenc.NewState()
	m.Preencode(s)
	return s.End
}

func preencodeFrame(state *cenc.State, m cenc.Marshaler) {
	n := frameSize(m)
	cenc.NewUint().Preencode(state, n)
	state.End += n
}

func encodeFrame(state *cenc.State, m cenc.Marshaler) error {
	if err := cenc.NewUint().Encode(state, frameSize(m)); err != nil {
		return err
	}
	return m.Encode(state)
}

func decodeFrame(state *cenc.State, m cenc.Unmarshaler) error {
	n, err := cenc.NewUint().Decode(state)
	if err != nil {
		return err
	}
	if state.End-state.Start < n {
		return cenc.NewEncodingErrorOutOfBounds()
	}
	end := state.End
	state.End = state.Start + n
	err = m.Decode(state)
	state.Start, state.End = state.End, end
	return err
}
