// This file is autogenerated by the hrpc compiler
package hrpc

import (
	"context"
	"errors"
	"io"

	bare_rpc "github.com/holepunchto/bare-rpc-golang"
	cenc "github.com/holepunchto/compact-encoding-golang"

	schema "github.com/holepunchto/bareclaw/schema"
)

// ErrNoHandler is replied when a command is not implemented on the serving side.
var ErrNoHandler = &bare_rpc.RPCError{Message: "No handler registered", Code: "NO_HANDLER"}

// ErrUnexpectedEvent fails the channel when a command that expects a reply arrives as an event.
var ErrUnexpectedEvent = errors.New("hrpc: request command received as event")

// Server is implemented by the side that serves these commands; embed UnimplementedServer to serve a subset.
type Server interface {
	Chat(ctx context.Context, request schema.BareclawChatRequest, out *SendStream[schema.BareclawChatChunk]) error
	SessionCreate(ctx context.Context, request schema.BareclawSessionScope) (schema.BareclawSessionKey, error)
	SessionList(ctx context.Context, request schema.BareclawEmpty) (schema.BareclawSessionList, error)
	SessionExport(ctx context.Context, request schema.BareclawSessionKey) (schema.BareclawSessionBlob, error)
	SessionImport(ctx context.Context, request schema.BareclawSessionBlob) (schema.BareclawEmpty, error)
	StateExport(ctx context.Context, request schema.BareclawEmpty) (schema.BareclawStateBlob, error)
	StateImport(ctx context.Context, request schema.BareclawStateBlob) (schema.BareclawEmpty, error)
	ToolRegister(ctx context.Context, request schema.BareclawToolDef) (schema.BareclawEmpty, error)
	ToolExec(ctx context.Context, request schema.BareclawToolCall) (schema.BareclawToolResult, error)
	StateChanged(ctx context.Context, request schema.BareclawStateChunk)
}

// UnimplementedServer rejects every command with ErrNoHandler.
type UnimplementedServer struct{}

func (UnimplementedServer) Chat(ctx context.Context, request schema.BareclawChatRequest, out *SendStream[schema.BareclawChatChunk]) error {
	return ErrNoHandler
}

func (UnimplementedServer) SessionCreate(ctx context.Context, request schema.BareclawSessionScope) (schema.BareclawSessionKey, error) {
	var zero schema.BareclawSessionKey
	return zero, ErrNoHandler
}

func (UnimplementedServer) SessionList(ctx context.Context, request schema.BareclawEmpty) (schema.BareclawSessionList, error) {
	var zero schema.BareclawSessionList
	return zero, ErrNoHandler
}

func (UnimplementedServer) SessionExport(ctx context.Context, request schema.BareclawSessionKey) (schema.BareclawSessionBlob, error) {
	var zero schema.BareclawSessionBlob
	return zero, ErrNoHandler
}

func (UnimplementedServer) SessionImport(ctx context.Context, request schema.BareclawSessionBlob) (schema.BareclawEmpty, error) {
	var zero schema.BareclawEmpty
	return zero, ErrNoHandler
}

func (UnimplementedServer) StateExport(ctx context.Context, request schema.BareclawEmpty) (schema.BareclawStateBlob, error) {
	var zero schema.BareclawStateBlob
	return zero, ErrNoHandler
}

func (UnimplementedServer) StateImport(ctx context.Context, request schema.BareclawStateBlob) (schema.BareclawEmpty, error) {
	var zero schema.BareclawEmpty
	return zero, ErrNoHandler
}

func (UnimplementedServer) ToolRegister(ctx context.Context, request schema.BareclawToolDef) (schema.BareclawEmpty, error) {
	var zero schema.BareclawEmpty
	return zero, ErrNoHandler
}

func (UnimplementedServer) ToolExec(ctx context.Context, request schema.BareclawToolCall) (schema.BareclawToolResult, error) {
	var zero schema.BareclawToolResult
	return zero, ErrNoHandler
}

func (UnimplementedServer) StateChanged(ctx context.Context, request schema.BareclawStateChunk) {
}

// HRPC is the typed client for this schema over one bare-rpc channel, serving the given Server on it too.
type HRPC struct {
	rpc    *bare_rpc.RPC
	server Server
	ctx    context.Context
	cancel context.CancelFunc
	done   chan struct{}
	err    error
}

// New starts serving on stream. server may be nil for a client-only side.
func New(stream io.ReadWriter, server Server) *HRPC {
	ctx, cancel := context.WithCancel(context.Background())
	h := &HRPC{rpc: bare_rpc.NewRPC(stream), server: server, ctx: ctx, cancel: cancel, done: make(chan struct{})}
	go h.listen()
	return h
}

func (h *HRPC) listen() {
	h.err = h.rpc.Listen(h.onRequest)
	h.cancel()
	close(h.done)
}

// RPC returns the underlying bare-rpc channel.
func (h *HRPC) RPC() *bare_rpc.RPC {
	return h.rpc
}

// Done is closed once the channel has ended; handler contexts are cancelled at the same time.
func (h *HRPC) Done() <-chan struct{} {
	return h.done
}

// Err reports why the channel ended (io.EOF for a clean close), or nil while it is still running.
func (h *HRPC) Err() error {
	select {
	case <-h.done:
		return h.err
	default:
		return nil
	}
}

// Close fails everything in flight and closes the transport.
func (h *HRPC) Close() error {
	return h.rpc.Close()
}

// Chat calls @bareclaw/chat and returns its stream of responses.
func (h *HRPC) Chat(request schema.BareclawChatRequest) (*RecvStream[schema.BareclawChatChunk], error) {
	data, err := encode(request)
	if err != nil {
		return nil, err
	}
	req := h.rpc.NewRequest(0)
	stream := req.CreateResponseStream() // registered first so an error reply cannot race it
	if err := req.Send(data); err != nil {
		stream.Close()
		return nil, err
	}
	return &RecvStream[schema.BareclawChatChunk]{stream: stream}, nil
}

// SessionCreate calls @bareclaw/session-create and waits for its reply.
func (h *HRPC) SessionCreate(ctx context.Context, request schema.BareclawSessionScope) (schema.BareclawSessionKey, error) {
	var response schema.BareclawSessionKey
	data, err := encode(request)
	if err != nil {
		return response, err
	}
	req := h.rpc.NewRequest(1)
	if err := req.Send(data); err != nil {
		return response, err
	}
	data, err = req.ReplyContext(ctx)
	if err != nil {
		return response, err
	}
	return response, decode(data, &response)
}

// SessionList calls @bareclaw/session-list and waits for its reply.
func (h *HRPC) SessionList(ctx context.Context, request schema.BareclawEmpty) (schema.BareclawSessionList, error) {
	var response schema.BareclawSessionList
	data, err := encode(request)
	if err != nil {
		return response, err
	}
	req := h.rpc.NewRequest(2)
	if err := req.Send(data); err != nil {
		return response, err
	}
	data, err = req.ReplyContext(ctx)
	if err != nil {
		return response, err
	}
	return response, decode(data, &response)
}

// SessionExport calls @bareclaw/session-export and waits for its reply.
func (h *HRPC) SessionExport(ctx context.Context, request schema.BareclawSessionKey) (schema.BareclawSessionBlob, error) {
	var response schema.BareclawSessionBlob
	data, err := encode(request)
	if err != nil {
		return response, err
	}
	req := h.rpc.NewRequest(3)
	if err := req.Send(data); err != nil {
		return response, err
	}
	data, err = req.ReplyContext(ctx)
	if err != nil {
		return response, err
	}
	return response, decode(data, &response)
}

// SessionImport calls @bareclaw/session-import and waits for its reply.
func (h *HRPC) SessionImport(ctx context.Context, request schema.BareclawSessionBlob) (schema.BareclawEmpty, error) {
	var response schema.BareclawEmpty
	data, err := encode(request)
	if err != nil {
		return response, err
	}
	req := h.rpc.NewRequest(4)
	if err := req.Send(data); err != nil {
		return response, err
	}
	data, err = req.ReplyContext(ctx)
	if err != nil {
		return response, err
	}
	return response, decode(data, &response)
}

// StateExport calls @bareclaw/state-export and waits for its reply.
func (h *HRPC) StateExport(ctx context.Context, request schema.BareclawEmpty) (schema.BareclawStateBlob, error) {
	var response schema.BareclawStateBlob
	data, err := encode(request)
	if err != nil {
		return response, err
	}
	req := h.rpc.NewRequest(5)
	if err := req.Send(data); err != nil {
		return response, err
	}
	data, err = req.ReplyContext(ctx)
	if err != nil {
		return response, err
	}
	return response, decode(data, &response)
}

// StateImport calls @bareclaw/state-import and waits for its reply.
func (h *HRPC) StateImport(ctx context.Context, request schema.BareclawStateBlob) (schema.BareclawEmpty, error) {
	var response schema.BareclawEmpty
	data, err := encode(request)
	if err != nil {
		return response, err
	}
	req := h.rpc.NewRequest(6)
	if err := req.Send(data); err != nil {
		return response, err
	}
	data, err = req.ReplyContext(ctx)
	if err != nil {
		return response, err
	}
	return response, decode(data, &response)
}

// ToolRegister calls @bareclaw/tool-register and waits for its reply.
func (h *HRPC) ToolRegister(ctx context.Context, request schema.BareclawToolDef) (schema.BareclawEmpty, error) {
	var response schema.BareclawEmpty
	data, err := encode(request)
	if err != nil {
		return response, err
	}
	req := h.rpc.NewRequest(7)
	if err := req.Send(data); err != nil {
		return response, err
	}
	data, err = req.ReplyContext(ctx)
	if err != nil {
		return response, err
	}
	return response, decode(data, &response)
}

// ToolExec calls @bareclaw/tool-exec and waits for its reply.
func (h *HRPC) ToolExec(ctx context.Context, request schema.BareclawToolCall) (schema.BareclawToolResult, error) {
	var response schema.BareclawToolResult
	data, err := encode(request)
	if err != nil {
		return response, err
	}
	req := h.rpc.NewRequest(8)
	if err := req.Send(data); err != nil {
		return response, err
	}
	data, err = req.ReplyContext(ctx)
	if err != nil {
		return response, err
	}
	return response, decode(data, &response)
}

// StateChanged sends @bareclaw/state-changed as a one-way event.
func (h *HRPC) StateChanged(request schema.BareclawStateChunk) error {
	data, err := encode(request)
	if err != nil {
		return err
	}
	return h.rpc.Event(9, data)
}

func (h *HRPC) onRequest(req *bare_rpc.Request) error {
	switch req.Command {
	case 0:
		return h.handleChat(req)
	case 1:
		return h.handleSessionCreate(req)
	case 2:
		return h.handleSessionList(req)
	case 3:
		return h.handleSessionExport(req)
	case 4:
		return h.handleSessionImport(req)
	case 5:
		return h.handleStateExport(req)
	case 6:
		return h.handleStateImport(req)
	case 7:
		return h.handleToolRegister(req)
	case 8:
		return h.handleToolExec(req)
	case 9:
		return h.handleStateChanged(req)
	}
	if req.IsEvent() {
		return nil
	}
	return ErrNoHandler
}

func (h *HRPC) handleChat(req *bare_rpc.Request) error {
	if req.IsEvent() {
		return ErrUnexpectedEvent
	}
	if h.server == nil {
		return ErrNoHandler
	}
	var request schema.BareclawChatRequest
	if err := decode(req.Data, &request); err != nil {
		return err
	}
	out := &SendStream[schema.BareclawChatChunk]{stream: req.CreateResponseStream()}
	if err := h.server.Chat(h.ctx, request, out); err != nil {
		return out.Destroy(err)
	}
	return out.Close()
}

func (h *HRPC) handleSessionCreate(req *bare_rpc.Request) error {
	if req.IsEvent() {
		return ErrUnexpectedEvent
	}
	if h.server == nil {
		return ErrNoHandler
	}
	var request schema.BareclawSessionScope
	if err := decode(req.Data, &request); err != nil {
		return err
	}
	response, err := h.server.SessionCreate(h.ctx, request)
	if err != nil {
		return err
	}
	data, err := encode(response)
	if err != nil {
		return err
	}
	return req.Reply(data)
}

func (h *HRPC) handleSessionList(req *bare_rpc.Request) error {
	if req.IsEvent() {
		return ErrUnexpectedEvent
	}
	if h.server == nil {
		return ErrNoHandler
	}
	var request schema.BareclawEmpty
	if err := decode(req.Data, &request); err != nil {
		return err
	}
	response, err := h.server.SessionList(h.ctx, request)
	if err != nil {
		return err
	}
	data, err := encode(response)
	if err != nil {
		return err
	}
	return req.Reply(data)
}

func (h *HRPC) handleSessionExport(req *bare_rpc.Request) error {
	if req.IsEvent() {
		return ErrUnexpectedEvent
	}
	if h.server == nil {
		return ErrNoHandler
	}
	var request schema.BareclawSessionKey
	if err := decode(req.Data, &request); err != nil {
		return err
	}
	response, err := h.server.SessionExport(h.ctx, request)
	if err != nil {
		return err
	}
	data, err := encode(response)
	if err != nil {
		return err
	}
	return req.Reply(data)
}

func (h *HRPC) handleSessionImport(req *bare_rpc.Request) error {
	if req.IsEvent() {
		return ErrUnexpectedEvent
	}
	if h.server == nil {
		return ErrNoHandler
	}
	var request schema.BareclawSessionBlob
	if err := decode(req.Data, &request); err != nil {
		return err
	}
	response, err := h.server.SessionImport(h.ctx, request)
	if err != nil {
		return err
	}
	data, err := encode(response)
	if err != nil {
		return err
	}
	return req.Reply(data)
}

func (h *HRPC) handleStateExport(req *bare_rpc.Request) error {
	if req.IsEvent() {
		return ErrUnexpectedEvent
	}
	if h.server == nil {
		return ErrNoHandler
	}
	var request schema.BareclawEmpty
	if err := decode(req.Data, &request); err != nil {
		return err
	}
	response, err := h.server.StateExport(h.ctx, request)
	if err != nil {
		return err
	}
	data, err := encode(response)
	if err != nil {
		return err
	}
	return req.Reply(data)
}

func (h *HRPC) handleStateImport(req *bare_rpc.Request) error {
	if req.IsEvent() {
		return ErrUnexpectedEvent
	}
	if h.server == nil {
		return ErrNoHandler
	}
	var request schema.BareclawStateBlob
	if err := decode(req.Data, &request); err != nil {
		return err
	}
	response, err := h.server.StateImport(h.ctx, request)
	if err != nil {
		return err
	}
	data, err := encode(response)
	if err != nil {
		return err
	}
	return req.Reply(data)
}

func (h *HRPC) handleToolRegister(req *bare_rpc.Request) error {
	if req.IsEvent() {
		return ErrUnexpectedEvent
	}
	if h.server == nil {
		return ErrNoHandler
	}
	var request schema.BareclawToolDef
	if err := decode(req.Data, &request); err != nil {
		return err
	}
	response, err := h.server.ToolRegister(h.ctx, request)
	if err != nil {
		return err
	}
	data, err := encode(response)
	if err != nil {
		return err
	}
	return req.Reply(data)
}

func (h *HRPC) handleToolExec(req *bare_rpc.Request) error {
	if req.IsEvent() {
		return ErrUnexpectedEvent
	}
	if h.server == nil {
		return ErrNoHandler
	}
	var request schema.BareclawToolCall
	if err := decode(req.Data, &request); err != nil {
		return err
	}
	response, err := h.server.ToolExec(h.ctx, request)
	if err != nil {
		return err
	}
	data, err := encode(response)
	if err != nil {
		return err
	}
	return req.Reply(data)
}

func (h *HRPC) handleStateChanged(req *bare_rpc.Request) error {
	if h.server == nil {
		return nil
	}
	var request schema.BareclawStateChunk
	if err := decode(req.Data, &request); err != nil {
		return err
	}
	h.server.StateChanged(h.ctx, request)
	return nil
}

func encode(v any) ([]byte, error) {
	return cenc.Marshal(v)
}

// decode leaves v zero for an absent payload (undefined arguments on the JavaScript side).
func decode(data []byte, v any) error {
	if len(data) == 0 {
		return nil
	}
	return cenc.Unmarshal(data, v)
}

// RecvStream yields the typed messages of an incoming stream.
type RecvStream[T any] struct {
	stream *bare_rpc.IncomingStream
}

// Recv returns the next message, or io.EOF once the remote end has finished.
func (s *RecvStream[T]) Recv() (T, error) {
	var v T
	data, err := s.stream.ReadChunk()
	if err != nil {
		return v, err
	}
	return v, decode(data, &v)
}

// Close stops receiving and tells the remote sender to stop.
func (s *RecvStream[T]) Close() error {
	return s.stream.Close()
}

// Destroy stops receiving and tells the remote sender why.
func (s *RecvStream[T]) Destroy(err error) error {
	return s.stream.Destroy(err)
}

// SendStream sends typed messages on an outgoing stream, one frame each.
type SendStream[T any] struct {
	stream *bare_rpc.OutgoingStream
}

// Send encodes and sends one message, blocking while the receiver has paused the stream.
func (s *SendStream[T]) Send(v T) error {
	data, err := encode(v)
	if err != nil {
		return err
	}
	_, err = s.stream.Write(data)
	return err
}

// Close ends the stream gracefully.
func (s *SendStream[T]) Close() error {
	return s.stream.Close()
}

// Destroy aborts the stream, telling the receiver why.
func (s *SendStream[T]) Destroy(err error) error {
	return s.stream.Destroy(err)
}
